apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendation-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/itaymosco/final_project
    targetRevision: HEAD
    path: ./mychart
    helm:
      parameters:
        - name: image.repository
          value: itay1608/recommendation_app
        - name: image.tag
          value: latest
        - name: image.pullPolicy
          value: Always
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
